*/*: sync with upstream
Taken from: HardenedBSD

diff --git a/sysutils/debootstrap/files/patch-scripts-gutsy b/sysutils/debootstrap/files/patch-scripts-gutsy
--- a/sysutils/debootstrap/files/patch-scripts-gutsy
+++ b/sysutils/debootstrap/files/patch-scripts-gutsy
@@ -1,6 +1,28 @@
---- scripts/gutsy.orig	2020-07-08 20:51:17.590645000 +0100
-+++ scripts/gutsy	2020-07-08 20:51:28.786509000 +0100
-@@ -249,10 +249,13 @@ echo \"Warning: Fake initctl called, doing nothing\"" 
+--- scripts/gutsy.orig	2020-03-13 02:04:21 UTC
++++ scripts/gutsy
+@@ -242,10 +242,21 @@ echo \"Warning: Fake initctl called, doing nothing\"" 
+ 		predep=$(without "$(without "$(resolve_deps $predep)" "$required")" "$done_predeps")
+ 		# XXX: progress is tricky due to how dpkg_progress works
+ 		# -- cjwatson 2009-07-29
++		# This step sometimes fails due to some missing functionality in Linuxulator.  Just ignore it.
++		set +e
+ 		p; smallyes '' |
+ 		in_target dpkg --force-overwrite --force-confold --skip-same-version --install $(debfor $predep)
++		rc=$?
+ 		base=$(without "$base" "$predep")
+ 		done_predeps="$done_predeps $predep"
++
++		if [ $rc != 0 ]; then
++			warning FREEBSD_00 "Applying FreeBSD-specific workaround..."
++			# ... for "Failed to mount /etc/machine-id: Bad address" with Focal.
++			in_target truncate -s0 /var/lib/dpkg/info/systemd.postinst
++			in_target dpkg --configure systemd
++		fi
++		set -e
+ 	done
+ 
+ 	if [ -n "$base" ]; then
+@@ -256,10 +267,13 @@ echo \"Warning: Fake initctl called, doing nothing\"" 
  
  		info CONFBASE "Configuring the base system..."
  
