security/suricata: fix ifdef, revert configure glue

diff --git a/security/suricata/files/patch-netmap-compat b/security/suricata/files/patch-netmap-compat
--- a/security/suricata/files/patch-netmap-compat
+++ b/security/suricata/files/patch-netmap-compat
@@ -1,3 +1,75 @@
+diff --git configure.ac configure.ac
+index ea5019422..5dcc63aaf 100644
+--- configure.ac
++++ configure.ac
+@@ -1481,16 +1481,11 @@
+     ])
+ 
+   # Netmap support
+-    AC_ARG_ENABLE(netmap_v14,
+-            AS_HELP_STRING([--enable-netmap-v14], [Enable Netmap v14+ support]),[enable_netmap_v14=$enableval],[enable_netmap_v14=no])
+     AC_ARG_ENABLE(netmap,
+             AS_HELP_STRING([--enable-netmap], [Enable Netmap support]),[enable_netmap=$enableval],[enable_netmap=no])
+     AC_ARG_WITH(netmap_includes,
+             [  --with-netmap-includes=DIR netmap include directory],
+             [with_netmap_includes="$withval"],[with_netmap_includes=no])
+-    AC_ARG_WITH(netmap_libraries,
+-            [  --with-netmap-libraries=DIR netmap library directory],
+-            [with_netmap_libraries="$withval"],[with_netmap_libraries=no])
+ 
+     AS_IF([test "x$enable_netmap" = "xyes"], [
+         AC_DEFINE([HAVE_NETMAP],[1],(NETMAP support enabled))
+@@ -1499,10 +1494,6 @@
+             CPPFLAGS="${CPPFLAGS} -I${with_netmap_includes}"
+         fi
+ 
+-        if test "$with_netmap_libraries" != "no"; then
+-            LDFLAGS="${LDFLAGS} -L${with_netmap_libraries}"
+-        fi
+-
+         AC_CHECK_HEADER(net/netmap_user.h,,[AC_MSG_ERROR(net/netmap_user.h not found ...)],)
+ 
+         have_recent_netmap="no"
+@@ -1563,29 +1554,7 @@
+         #endif
+         ])], [have_gtv13_netmap="yes"])
+         if test "x$have_gtv13_netmap" = "xyes"; then
+-            have_netmap_version="v14+"
+-            if test "x$enable_netmap_v14" = "xyes"; then
+-                AC_CHECK_HEADER(libnetmap.h,,[AC_MSG_ERROR(libnetmap.h not found ...)],)
+-                LIBNETMAP=""
+-                AC_SEARCH_LIBS([nmport_open],[netmap],,[LIBNETMAP="no"])
+-                if test "$LIBNETMAP" = "no"; then
+-                    echo
+-                    echo "   ERROR!  libnetmap library not found!"
+-                    echo "   Go get it from https://github.com/luigirizzo/netmap"
+-                    echo "   or your distribution."
+-                    echo
+-                    exit 1
+-                fi
+-                AC_DEFINE([USE_NEW_NETMAP_API],[1],(NETMAP new support enabled))
+-            else
+-                echo
+-                echo "Notice: Netmap version v14+ found."
+-                echo "To the new Netmap APIs from this version, use the"
+-                echo "--enable-netmap-v14 option."
+-                echo
+-                echo "Using legacy Netmap APIs; reconfigure if the new APIs should be used"
+-                echo
+-            fi
++            have_netmap_version="> v13"
+         fi
+   ])
+ 
+@@ -2814,7 +2783,7 @@ SURICATA_BUILD_CONF="Suricata Configuration:
+   NFQueue support:                         ${enable_nfqueue}
+   NFLOG support:                           ${enable_nflog}
+   IPFW support:                            ${enable_ipfw}
+-  Netmap support:                          ${enable_netmap} ${have_netmap_version} [using new api: $enable_netmap_v14]
++  Netmap support:                          ${enable_netmap} ${have_netmap_version}
+   DAG enabled:                             ${enable_dag}
+   Napatech enabled:                        ${enable_napatech}
+   WinDivert enabled:                       ${enable_windivert}
 diff --git src/source-netmap.c src/source-netmap.c
 index 00b4400b4..0e1ac70c8 100644
 --- src/source-netmap.c
